trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Checkout@1
  displayName: 'Checkout code from GitHub'


- task: AzureCLI@2
  displayName: 'Login to Azure'
  inputs:
    azureSubscription: 'devopsR'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Logging into Azure..."


- task: AzureWebAppContainer@1
  displayName: 'Deploy Docker Container to Azure Web App'
  inputs:
    azureSubscription: 'devopsR'
    appName: 'dc-cloud-ankita-webapp'
    imageName: 'dccloudankita.azurecr.io/myapp:latest'
    containerRegistry: 'dccloudankita'
    isMultiContainer: false

